name: Deploy Angular App

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - fix-deploy

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
  REMOTE_DIR: ${{ secrets.REMOTE_DIR || '/var/www/html' }}

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Validate SSH Key
        run: |
          echo "Key length: ${#TEST_KEY}"
          echo "$TEST_KEY" | head -n 3
          echo "$TEST_KEY" | tail -n 3
        env:
          TEST_KEY: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Create deployment archive
        run: |
          cd dist/bookIT-admin-front/browser
          tar -czf ../deploy.tar.gz .

      - name: Deploy to server
        run: |
          scp -o StrictHostKeyChecking=no -P $SSH_PORT dist/bookIT-admin-front/deploy.tar.gz $SSH_USER@$SSH_HOST:/home/$SSH_USER
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "
            sudo mkdir -p $REMOTE_DIR
            sudo rm -rf $REMOTE_DIR/*
            sudo tar -xzf /home/$SSH_USER/deploy.tar.gz -C $REMOTE_DIR
            sudo chown -R www-data:www-data $REMOTE_DIR
            rm /home/$SSH_USER/deploy.tar.gz
          "

      - name: Cleanup
        run: rm -f dist/deploy.tar.gz
